<!DOCTYPE html>
<html lang="en"><head>
<script src="clase03_metalectura_presentacion-2_files/libs/clipboard/clipboard.min.js"></script>
<script src="clase03_metalectura_presentacion-2_files/libs/quarto-html/tabby.min.js"></script>
<script src="clase03_metalectura_presentacion-2_files/libs/quarto-html/popper.min.js"></script>
<script src="clase03_metalectura_presentacion-2_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="clase03_metalectura_presentacion-2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="clase03_metalectura_presentacion-2_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="clase03_metalectura_presentacion-2_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Mauricio Apablaza">
  <title>Problemas públicos complejos e interdisciplinariedad</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="clase03_metalectura_presentacion-2_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="clase03_metalectura_presentacion-2_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="clase03_metalectura_presentacion-2_files/libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link rel="stylesheet" href="styles.css">
  <link href="clase03_metalectura_presentacion-2_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="clase03_metalectura_presentacion-2_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="clase03_metalectura_presentacion-2_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="clase03_metalectura_presentacion-2_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title"><span style="color: #e67e22;">Problemas públicos complejos</span> e interdisciplinariedad</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Mauricio Apablaza 
</div>
</div>
</div>

</section>
<section id="lo-que-haremos-en-esta-hora" class="title-slide slide level1 center">
<h1>Lo que haremos en esta hora</h1>
<p>Empezamos por algo que ustedes usan todos los días sin definirlo: qué es una disciplina y quién decide dónde termina la suya. Vamos a ver que la disciplina no es una etiqueta intelectual sino una infraestructura concreta de revistas, departamentos, acreditaciones y grupos de evaluación de la ANID, que decide quién juzga su trabajo antes de que usted lo escriba.</p>
<p>Con eso encima distinguimos multidisciplina, interdisciplina y transdisciplina, que no son grados de entusiasmo colaborativo sino tres cosas distintas con consecuencias distintas.</p>
<p>La segunda mitad es práctica. Reconstruimos el argumento de dos artículos reales de campos distintos, buscamos la premisa que ninguno de los dos escribió, y mostramos que esa premisa es exactamente lo que decide si un trabajo es interdisciplinario de verdad o solo en la bibliografía.</p>
</section>

<section id="qué-es-una-disciplina" class="title-slide slide level1 center">
<h1>Qué es una <span style="color: #e67e22;">disciplina</span></h1>
<p>Una disciplina no es un conjunto de temas. Es un acuerdo estabilizado sobre tres cosas: qué cuenta como un fenómeno digno de estudio, qué procedimiento produce una prueba aceptable y quién está autorizado a juzgar si el trabajo está bien hecho.</p>
<p>Ese acuerdo no vive en las cabezas de los investigadores. Vive en instituciones que ustedes ya conocen y que operan todos los días sobre su carrera.</p>
</section>

<section id="los-cinco-elementos-de-una-disciplina" class="title-slide slide level1 center">
<h1>Los cinco elementos de una <span style="color: #e67e22;">disciplina</span></h1>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Elemento</th>
<th style="text-align: left;">Qué fija</th>
<th style="text-align: left;">Dónde lo encuentra usted</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Un objeto propio</td>
<td style="text-align: left;">Qué fenómeno merece ser explicado</td>
<td style="text-align: left;">La psicología explica al individuo y sus atributos; la ciencia política explica la autoridad y su ejercicio</td>
</tr>
<tr class="even">
<td style="text-align: left;">Un método aceptado</td>
<td style="text-align: left;">Qué procedimiento produce prueba válida</td>
<td style="text-align: left;">Un psicómetra le pedirá validez y confiabilidad de la escala; un politólogo le pedirá identificación causal o una lectura fundada del texto</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Un sistema de revistas</td>
<td style="text-align: left;">Dónde se publica y quién arbitra</td>
<td style="text-align: left;">Los dos artículos de hoy fueron a revistas distintas, con árbitros que no se leen entre sí</td>
</tr>
<tr class="even">
<td style="text-align: left;">Una estructura de formación</td>
<td style="text-align: left;">Quién queda habilitado para firmar</td>
<td style="text-align: left;">Facultades, departamentos, doctorados y sus mallas producen al autor competente</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Una vía de financiamiento</td>
<td style="text-align: left;">Quién juzga el proyecto antes de que exista</td>
<td style="text-align: left;">Los grupos de evaluación de Fondecyt deciden si el proyecto se financia</td>
</tr>
</tbody>
</table>
<p>Cambiar de disciplina no es cambiar de tema. Es cambiar de tribunal.</p>
</section>

<section id="dónde-está-la-frontera-disciplinaria" class="title-slide slide level1 center">
<h1>Dónde está la frontera <span style="color: #e67e22;">disciplinaria</span></h1>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Instancia</th>
<th style="text-align: left;">Regla que opera</th>
<th style="text-align: left;">Consecuencia práctica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Indexación de revistas</td>
<td style="text-align: left;">Web of Science y Scopus asignan cada revista a una o más categorías temáticas</td>
<td style="text-align: left;">El cuartil se calcula dentro de la categoría, de modo que una misma revista puede ser Q1 en una y Q2 en otra</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conteo institucional</td>
<td style="text-align: left;">Las universidades reportan publicaciones por facultad y por área del conocimiento</td>
<td style="text-align: left;">El trabajo que no cabe en un área se reporta mal, se reparte o simplemente no se cuenta</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Acreditación</td>
<td style="text-align: left;">Los programas de postgrado se evalúan según estándares del área a la que se adscriben</td>
<td style="text-align: left;">El comité aplica criterios de una disciplina aunque el programa se declare interdisciplinario</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fondecyt</td>
<td style="text-align: left;">Los proyectos se distribuyen en 30 grupos de evaluación agrupados en cuatro áreas</td>
<td style="text-align: left;">El postulante elige el grupo al postular y las bases no admiten cambios en ninguna etapa</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Conflicto de interés</td>
<td style="text-align: left;">Pertenecer a la misma facultad o departamento inhabilita para evaluar</td>
<td style="text-align: left;">La unidad administrativa define quién puede juzgar su trabajo y quién no</td>
</tr>
</tbody>
</table>
</section>

<section id="las-cuatro-áreas-de-evaluación-de-fondecyt" class="title-slide slide level1 center">
<h1>Las cuatro áreas de evaluación de <span style="color: #e67e22;">Fondecyt</span></h1>
<p>Los 30 grupos de evaluación se organizan en cuatro coordinaciones de área: artes, ciencias sociales y humanidades; ciencias naturales y de la vida; ciencias exactas y de la ingeniería; e interdisciplina y transdisciplina.</p>
<p>La cuarta área es reciente. Se creó en torno a 2020, partió con Iniciación y luego incorporó Regular. Su existencia dice algo importante: la agencia reconoció que había proyectos que llegaban a los grupos disciplinarios y no podían evaluarse bien ahí, y en lugar de forzarlos creó un tribunal aparte.</p>
<p>Para postular a esa área las bases exigen una condición precisa, y es la misma que vamos a trabajar toda la clase: la propuesta debe responder una pregunta que solo puede ser abordada de forma inter o transdisciplinaria.</p>
</section>

<section id="multi-inter-y-trans-no-son-grados-de-entusiasmo" class="title-slide slide level1 center">
<h1>Multi, inter y trans no son grados de entusiasmo</h1>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Forma</th>
<th style="text-align: left;">Qué ocurre con la pregunta</th>
<th style="text-align: left;">Quién participa</th>
<th style="text-align: left;">Cómo se reconoce al leer un texto</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Multidisciplina</td>
<td style="text-align: left;">Cada disciplina conserva su propia pregunta sobre un tema compartido</td>
<td style="text-align: left;">Académicos de varios campos, trabajando en paralelo</td>
<td style="text-align: left;">Las secciones están yuxtapuestas y las conclusiones de cada parte no se tocan entre sí</td>
</tr>
<tr class="even">
<td style="text-align: left;">Interdisciplina</td>
<td style="text-align: left;">Hay una pregunta común que ninguna disciplina puede responder sola</td>
<td style="text-align: left;">Académicos de varios campos, integrados en un mismo diseño</td>
<td style="text-align: left;">Los conceptos o métodos de un campo entran efectivamente en el diseño del otro</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Transdisciplina</td>
<td style="text-align: left;">La pregunta se formula junto a quienes viven el problema</td>
<td style="text-align: left;">Académicos y actores no académicos: servicios públicos, escuelas, comunidades</td>
<td style="text-align: left;">Aparecen decisiones de diseño que fueron tomadas con actores externos, no solo consultas</td>
</tr>
</tbody>
</table>
<p>La prueba para distinguirlas es sacar una disciplina del proyecto. Si el trabajo sobrevive amputado, era multidisciplina.</p>
</section>

<section id="la-definición-de-anidno-es-la-de-la-literatura" class="title-slide slide level1 center">
<h1>La definición de <span style="color: #e67e22;">ANID</span>no es la de la literatura</h1>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Bases de Fondecyt</th>
<th style="text-align: left;">Literatura internacional</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Interdisciplina</td>
<td style="text-align: left;">El tema y la pregunta integran distintas disciplinas y enfoques metodológicos</td>
<td style="text-align: left;">Coincide en lo esencial: hay integración conceptual y metodológica, no suma</td>
</tr>
<tr class="even">
<td style="text-align: left;">Transdisciplina</td>
<td style="text-align: left;">La pregunta cruza transversalmente varias disciplinas y genera conocimiento que no podría producirse con ellas por separado</td>
<td style="text-align: left;">Exige además coproducción con actores no académicos, en la línea de Gibbons y otros (1994) y Lang y otros (2012)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diferencia de fondo</td>
<td style="text-align: left;">Lo trans se define por la intensidad del cruce entre disciplinas</td>
<td style="text-align: left;">Lo trans se define por quién participa en producir el conocimiento</td>
</tr>
</tbody>
</table>
<p>Esto importa al postular. Un proyecto que en la literatura sería transdisciplinario porque coproduce con un servicio público puede ser leído por la agencia como interdisciplinario, y al revés. Conviene declarar cuál definición se está usando.</p>
</section>

<section id="por-qué-esto-obliga-a-leer-distinto" class="title-slide slide level1 center">
<h1>Por qué esto obliga a leer distinto</h1>
<p>Si la disciplina fija qué cuenta como prueba, entonces dos textos rigurosos sobre el mismo problema pueden estar en desacuerdo sin contradecirse en ningún dato. El desacuerdo está antes, en la premisa que autoriza a pasar de la evidencia a la conclusión.</p>
<p>Esa premisa casi nunca está escrita, porque dentro de cada campo es lo obvio. Lo que sigue es un procedimiento para escribirla.</p>
</section>

<section id="los-dos-textos-de-hoy" class="title-slide slide level1 center">
<h1>Los dos textos de hoy</h1>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Varela y otros (2026)</th>
<th style="text-align: left;">Raveau y otros (2024)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Campo</td>
<td style="text-align: left;">Psicología educacional y salud mental escolar</td>
<td style="text-align: left;">Ciencia política con lingüística computacional</td>
</tr>
<tr class="even">
<td style="text-align: left;">Qué mide</td>
<td style="text-align: left;">Covitalidad, entendida como fortalezas socioemocionales</td>
<td style="text-align: left;">Populismo de izquierda en discursos presidenciales</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Datos</td>
<td style="text-align: left;">1.384 estudiantes chilenos de 5º a 9º básico, encuestados en 2019</td>
<td style="text-align: left;">290 discursos de 67 líderes en 18 países de habla hispana</td>
</tr>
<tr class="even">
<td style="text-align: left;">Método</td>
<td style="text-align: left;">Análisis de perfiles latentes y ANOVA entre perfiles</td>
<td style="text-align: left;">Regresión logística multinomial sobre el puntaje del Global Populism Database</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dónde termina</td>
<td style="text-align: left;">Propone tamizajes semestrales de covitalidad en las escuelas</td>
<td style="text-align: left;">Se detiene en caracterizar el discurso, sin clasificar líderes</td>
</tr>
</tbody>
</table>
<p>Ambos son de la UDD, ambos son sólidos y ambos convierten un constructo discutido en algo medible. Ahí empieza el trabajo de hoy.</p>
</section>

<section id="resumir-no-es-reconstruir" class="title-slide slide level1 center">
<h1>Resumir no es reconstruir</h1>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Lo que devuelve un resumen</th>
<th style="text-align: left;">Lo que devuelve una reconstrucción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Varela</td>
<td style="text-align: left;">Encuentra cuatro perfiles de covitalidad en escolares chilenos</td>
<td style="text-align: left;">Sostiene que existen cuatro tipos de estudiante y no cuatro tramos de un mismo continuo</td>
</tr>
<tr class="even">
<td style="text-align: left;">Raveau</td>
<td style="text-align: left;">Analiza discursos presidenciales con herramientas de lenguaje natural</td>
<td style="text-align: left;">Sostiene que la forma del habla, y no su contenido, revela la intención estratégica del hablante</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Para qué sirve</td>
<td style="text-align: left;">Para citar el artículo</td>
<td style="text-align: left;">Para objetarlo, extenderlo o contrastarlo con otro</td>
</tr>
</tbody>
</table>
<p>Prueba rápida: si después de leer usted puede citar el texto pero no puede escribir una objeción de dos líneas, leyó el contenido y perdió el argumento.</p>
</section>

<section id="las-cinco-piezas-del-argumento" class="title-slide slide level1 center">
<h1>Las cinco piezas del <span style="color: #e67e22;">argumento</span></h1>
<p>La segunda columna es la pregunta que le hago al texto. La tercera no habla del texto: habla de mi apunte, y describe lo que escribo cuando creo haber encontrado la pieza y en realidad no la encontré.</p>
<table class="caption-top">
<colgroup>
<col style="width: 14%">
<col style="width: 22%">
<col style="width: 26%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Pieza</th>
<th style="text-align: left;">Qué le pregunto al texto</th>
<th style="text-align: left;">Si mi apunte dice esto, fallé</th>
<th style="text-align: left;">Cómo queda en Varela</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Afirmación</td>
<td style="text-align: left;">¿Qué quiere que yo acepte?</td>
<td style="text-align: left;">“Estudia la covitalidad en escolares chilenos”</td>
<td style="text-align: left;">Hay cuatro tipos de estudiante, no cuatro niveles del mismo rasgo</td>
</tr>
<tr class="even">
<td style="text-align: left;">Razones</td>
<td style="text-align: left;">¿Por qué debería aceptarlo?</td>
<td style="text-align: left;">“Tiene método y resultados”</td>
<td style="text-align: left;">El BIC es mínimo en cuatro clases y los perfiles difieren en bullying y satisfacción vital</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Evidencia</td>
<td style="text-align: left;">¿Con qué respalda cada razón?</td>
<td style="text-align: left;">“Usa una muestra de 1.384 casos”</td>
<td style="text-align: left;">Medias de los cuatro dominios del SEHS-S, más ANOVA con post hoc de Tukey</td>
</tr>
<tr class="even">
<td style="text-align: left;">Garantía</td>
<td style="text-align: left;">¿Por qué esa evidencia autoriza esa conclusión?</td>
<td style="text-align: left;">“Aplica el paquete tidyLPA”</td>
<td style="text-align: left;">Una clase latente estimada corresponde a un tipo real de persona</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Objeción</td>
<td style="text-align: left;">¿Qué reconoce y con qué lo desactiva?</td>
<td style="text-align: left;">“Menciona limitaciones”</td>
<td style="text-align: left;">Admite entropía de 0,67 y responde con probabilidades de clasificación e interpretabilidad</td>
</tr>
</tbody>
</table>
<p>Las tres primeras piezas están escritas en el artículo. Las dos últimas hay que reconstruirlas.</p>
</section>

<section id="reconstrucción-del-texto-a-varela-y-otros" class="title-slide slide level1 center">
<h1>Reconstrucción del texto A: Varela y otros</h1>
<p>El texto sostiene que los adolescentes chilenos se distribuyen en cuatro perfiles ordenados de covitalidad, y que esos perfiles se asocian con bullying y con satisfacción vital. Lo sostiene porque el BIC alcanza su mínimo en la solución de cuatro clases, y porque las diferencias entre perfiles resultan significativas en los tres indicadores de bullying y en satisfacción vital. La evidencia consiste en un análisis de perfiles latentes sobre las medias de los cuatro dominios del SEHS-S en 1.384 estudiantes, más una serie de ANOVA con post hoc de Tukey. Esto solo funciona si el autorreporte de fortalezas mide la fortaleza y no su declaración, y si una clase latente recuperada con entropía de 0,67 corresponde a un tipo real de estudiante. El texto reconoce la entropía moderada y responde con el rango de probabilidades de clasificación y con el argumento de que la solución es interpretable.</p>
<p>Fíjense dónde aparece la palabra “tipo”. Nunca se defiende. Se asume.</p>
</section>

<section id="reconstrucción-del-texto-b-raveau-y-otros" class="title-slide slide level1 center">
<h1>Reconstrucción del texto B: Raveau y otros</h1>
<p>El texto sostiene que el populismo de izquierda puede identificarse mediante marcadores lingüísticos que no dependen del contenido del discurso. Lo sostiene porque las referencias al endogrupo y la emoción negativa predicen el puntaje del Global Populism Database, y porque el tiempo futuro y los conectores condicionales también lo predicen mientras la primera persona no lo hace. La evidencia consiste en una regresión logística multinomial sobre 290 discursos de 18 países, con controles de país, período, tipo de discurso e índice de democracia liberal. Esto solo funciona si el puntaje asignado a mano por codificadores mide populismo y no el juicio del codificador, y si la frecuencia agregada de una forma verbal indexa la intención de quien habla. El texto reconoce que el efecto de la tercera persona queda sin explicación y responde con una hipótesis exploratoria construida al leer treinta oraciones.</p>
<p>La cuarta frase es la que ningún resumen recupera.</p>
</section>

<section id="cómo-saber-si-su-reconstrucción-está-bien-hecha" class="title-slide slide level1 center">
<h1>Cómo saber si su reconstrucción está bien hecha</h1>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Prueba</th>
<th style="text-align: left;">Su reconstrucción pasa si</th>
<th style="text-align: left;">Su reconstrucción falla si</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Negación</td>
<td style="text-align: left;">Un colega competente podría sostener lo contrario sin ser irracional</td>
<td style="text-align: left;">Al negar la afirmación el resultado suena absurdo, lo que indica que era un tema</td>
</tr>
<tr class="even">
<td style="text-align: left;">Especificidad</td>
<td style="text-align: left;">La afirmación nombra población, mecanismo y período</td>
<td style="text-align: left;">La afirmación serviría igual para cualquier país y cualquier década</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Garantía enunciable</td>
<td style="text-align: left;">Usted puede completar la frase “esto solo funciona si…”</td>
<td style="text-align: left;">Usted solo puede repetir el diseño empírico con otras palabras</td>
</tr>
<tr class="even">
<td style="text-align: left;">Contraejemplo</td>
<td style="text-align: left;">Usted puede describir el mundo en que la afirmación sería falsa</td>
<td style="text-align: left;">No se le ocurre ninguno, lo que casi siempre significa que no entendió la tesis</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Uso</td>
<td style="text-align: left;">Usted puede escribir una objeción de dos líneas</td>
<td style="text-align: left;">Usted solo puede citar el artículo</td>
</tr>
</tbody>
</table>
<p>Cuatro de cinco es aprobar. Fallar la tercera invalida a las demás.</p>
</section>

<section id="ahora-la-parte-dificil" class="title-slide slide level1 center">
<h1>Ahora la parte <span style="color: #e67e22;">dificil</span></h1>
<p>Todo lo anterior se puede hacer con oficio y atención. Lo que viene, no.</p>
<p>Nombrar la garantía obliga a salir del texto y preguntar qué tendría que ser verdad del mundo para que esa evidencia autorice esa conclusión. Los autores no la escriben porque dentro de su campo nadie la discute. Ustedes tienen que escribirla por ellos.</p>
</section>

<section id="garantía-o-método" class="title-slide slide level1 center">
<h1>Garantía o método</h1>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Esto es método, no garantía</th>
<th style="text-align: left;">La garantía que hay detrás</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">“Estima perfiles latentes con cuatro indicadores continuos”</td>
<td style="text-align: left;">Una clase estadística estimada corresponde a un tipo de persona existente</td>
</tr>
<tr class="even">
<td style="text-align: left;">“Ajusta una multinomial con efectos fijos de país”</td>
<td style="text-align: left;">El puntaje que asignaron codificadores humanos es populismo y no la percepción de los codificadores</td>
</tr>
<tr class="odd">
<td style="text-align: left;">“Cuenta conectores condicionales por oración”</td>
<td style="text-align: left;">La frecuencia agregada de una forma gramatical revela la intención de quien habla</td>
</tr>
</tbody>
</table>
<p>El método dice qué se hizo. La garantía dice por qué haberlo hecho autoriza a concluir lo que se concluye. Un método impecable con garantía falsa produce un artículo publicado y equivocado.</p>
</section>

<section id="la-garantía-central-de-cada-texto" class="title-slide slide level1 center">
<h1>La garantía central de cada texto</h1>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Premisa que sostiene todo el argumento</th>
<th style="text-align: left;">Lo que queda fuera de discusión</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Varela</td>
<td style="text-align: left;">El perfil latente identifica un tipo de estudiante y no un tramo de un continuo</td>
<td style="text-align: left;">Que la escala mida la fortaleza socioemocional y no la disposición del alumno a declararla</td>
</tr>
<tr class="even">
<td style="text-align: left;">Raveau</td>
<td style="text-align: left;">La forma del habla indexa una intención estratégica de manipular</td>
<td style="text-align: left;">Que el codificador humano capte el fenómeno y no un estereotipo compartido de lo que suena populista</td>
</tr>
</tbody>
</table>
<p>Ninguna de las dos aparece escrita en su artículo. Ambas son discutibles. Ambas sostienen todo lo demás.</p>
</section>

<section id="prueba-del-contraejemplo-texto-a" class="title-slide slide level1 center">
<h1>Prueba del contraejemplo: texto A</h1>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Mundo que haría falsa la tesis</th>
<th style="text-align: left;">¿El texto lo bloquea?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Los cuatro perfiles son cortes arbitrarios de un continuo y no tipos distintos</td>
<td style="text-align: left;">No lo bloquea. Los cuatro perfiles resultan ordenados de menor a mayor y la competencia emocional casi no los separa</td>
</tr>
<tr class="even">
<td style="text-align: left;">Un indicador con baja consistencia interna entra igual al modelo como si midiera bien</td>
<td style="text-align: left;">No se discute. La dimensión de creencia en los otros reporta un alfa de 0,55 y se usa como indicador del análisis</td>
</tr>
<tr class="odd">
<td style="text-align: left;">El criterio de ajuste seguía mejorando después de cuatro clases</td>
<td style="text-align: left;">Se responde en parte: el AIC sigue bajando, pero el BIC y la entropía apoyan la solución de cuatro</td>
</tr>
<tr class="even">
<td style="text-align: left;">Que las niñas queden sobrerrepresentadas en los perfiles bajos contradice la literatura internacional</td>
<td style="text-align: left;">Se declara desconcertante y se deriva a investigación futura, sin revisar la garantía</td>
</tr>
</tbody>
</table>
<p>La última fila es la interesante. Un resultado que el marco no anticipa aparece como anomalía y no como amenaza a la premisa.</p>
</section>

<section id="prueba-del-contraejemplo-texto-b" class="title-slide slide level1 center">
<h1>Prueba del contraejemplo: texto B</h1>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Mundo que haría falsa la tesis</th>
<th style="text-align: left;">¿El texto lo bloquea?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Los marcadores predicen bien el juicio de los codificadores, pero el juicio de los codificadores no es el populismo</td>
<td style="text-align: left;">No se distingue una cosa de la otra en ningún momento del análisis</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sin casos de derecha en la muestra, los marcadores podrían ser de populismo en general o de retórica presidencial latinoamericana</td>
<td style="text-align: left;">La restricción se declara con honestidad como límite de datos, pero el título conserva la expresión “de izquierda”</td>
</tr>
<tr class="odd">
<td style="text-align: left;">La variación en el puntaje se concentra en unos pocos líderes muy populistas</td>
<td style="text-align: left;">Conviene verificar cuánta variación real queda una vez incluidos los efectos de país</td>
</tr>
<tr class="even">
<td style="text-align: left;">La intención de manipular se infiere de una frecuencia gramatical agregada</td>
<td style="text-align: left;">Se usa el verbo “sugiere”, que reconoce el problema sin desactivarlo</td>
</tr>
</tbody>
</table>
<p>Una restricción de datos terminó convertida en una delimitación conceptual. Ocurre en muchas tesis y casi nunca se detecta a tiempo.</p>
</section>

<section id="qué-pasa-cuando-los-dos-textos-se-leen-juntos" class="title-slide slide level1 center">
<h1>Qué pasa cuando los dos textos se leen juntos</h1>
<p>Por separado, cada artículo es sólido y cada objeción que hicimos es interna a su campo. Leídos uno contra el otro aparece algo que ninguno de los dos podía ver solo.</p>
<p>Los dos hacen exactamente el mismo movimiento. Y se separan justo al final, en el punto que le importa a un doctorado en políticas públicas.</p>
</section>

<section id="el-movimiento-que-ambos-comparten" class="title-slide slide level1 center">
<h1>El movimiento que ambos comparten</h1>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Constructo discutido</th>
<th style="text-align: left;">Instrumento que lo estabiliza</th>
<th style="text-align: left;">En qué termina convertido</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Varela</td>
<td style="text-align: left;">Covitalidad, un metaconstructo de fortalezas</td>
<td style="text-align: left;">Escala SEHS-S más análisis de perfiles latentes</td>
<td style="text-align: left;">El perfil pasa a nombrar al estudiante</td>
</tr>
<tr class="even">
<td style="text-align: left;">Raveau</td>
<td style="text-align: left;">Populismo, un concepto disputado hace décadas</td>
<td style="text-align: left;">Codificación holística del Global Populism Database</td>
<td style="text-align: left;">El puntaje pasa a nombrar al fenómeno</td>
</tr>
</tbody>
</table>
<p>En ambos casos un constructo teóricamente disputado se estabiliza por vía instrumental, y después el producto del instrumento se trata como si fuera el constructo. Ninguno de los dos lo escribe. Los dos lo hacen.</p>
</section>

<section id="dónde-se-separan" class="title-slide slide level1 center">
<h1>Dónde se separan</h1>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Hasta dónde deja viajar la categoría que midió</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Varela</td>
<td style="text-align: left;">Llega hasta el individuo y propone tamizajes semestrales de covitalidad en las escuelas, con una entropía que admite incertidumbre de clasificación</td>
</tr>
<tr class="even">
<td style="text-align: left;">Raveau</td>
<td style="text-align: left;">Se detiene antes y declara de forma explícita que caracteriza el discurso, no el populismo ni al líder que lo pronuncia</td>
</tr>
</tbody>
</table>
<p>La incertidumbre de clasificación es comparable en ambos. La decisión de detenerse o seguir no es metodológica sino normativa, y ninguno de los dos artículos la argumenta.</p>
<p>Esa asimetría es material de tesis para ustedes.</p>
</section>

<section id="de-la-tensión-a-la-pregunta" class="title-slide slide level1 center">
<h1>De la tensión a la pregunta</h1>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Forma de plantear la pregunta</th>
<th style="text-align: left;">Ejemplo</th>
<th style="text-align: left;">Por qué no sirve o por qué sí</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Por vacío</td>
<td style="text-align: left;">“No existen estudios que integren psicometría y diseño de política”</td>
<td style="text-align: left;">La ausencia de literatura no es un argumento; puede que nadie lo haya hecho porque no vale la pena</td>
</tr>
<tr class="even">
<td style="text-align: left;">Por suma</td>
<td style="text-align: left;">“Cómo combinar el enfoque psicométrico con el enfoque de política pública”</td>
<td style="text-align: left;">No es una pregunta empírica y no tiene respuesta posible</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Por condición</td>
<td style="text-align: left;">“Con qué nivel de error de clasificación un tamizaje escolar produce más asignación errónea que beneficio”</td>
<td style="text-align: left;">Es empírica, delimitada y exige las dos disciplinas a la vez</td>
</tr>
</tbody>
</table>
<p>La tercera pregunta no está en ninguno de los dos artículos. Aparece solo al ponerlos uno contra el otro.</p>
</section>

<section id="multi-inter-y-trans-sobre-este-mismo-caso" class="title-slide slide level1 center">
<h1>Multi, inter y trans sobre este mismo caso</h1>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Qué hago con los dos textos</th>
<th style="text-align: left;">Qué forma resulta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Los cito juntos en la revisión de literatura y cada uno conserva su pregunta</td>
<td style="text-align: left;">Multidisciplina. El trabajo sobrevive si elimino uno de los dos</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pregunto qué error de clasificación tolera un tamizaje escolar antes de dañar a quien pretende ayudar</td>
<td style="text-align: left;">Interdisciplina. Necesito psicometría para estimar el error y análisis de política para valorar sus consecuencias</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Defino junto a directivos, docentes y familias qué tipo de error es aceptable y cuál no</td>
<td style="text-align: left;">Transdisciplina. El criterio de aceptabilidad no lo puede fijar la academia sola</td>
</tr>
</tbody>
</table>
<p>Los tres escenarios son legítimos. Solo el segundo y el tercero justifican postular al área inter y transdisciplina de Fondecyt, porque solo ahí la pregunta deja de tener respuesta dentro de una disciplina.</p>
</section>

<section id="cómo-se-hace-esto-en-veinte-minutos-por-texto" class="title-slide slide level1 center">
<h1>Cómo se hace esto en veinte minutos por texto</h1>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Pasada</th>
<th style="text-align: left;">Qué busca</th>
<th style="text-align: left;">Cuándo se detiene</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Primera</td>
<td style="text-align: left;">La afirmación</td>
<td style="text-align: left;">Cuando logró escribir la frase “este texto sostiene que…” con sus propias palabras</td>
</tr>
<tr class="even">
<td style="text-align: left;">Segunda</td>
<td style="text-align: left;">Las razones</td>
<td style="text-align: left;">Cuando los encabezados de sección funcionan como una cadena de argumento y no como un índice</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tercera</td>
<td style="text-align: left;">La evidencia y la garantía</td>
<td style="text-align: left;">Cuando cubrió solo aquello que va a usar o a disputar, no el artículo completo</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<colgroup>
<col style="width: 48%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">En vez de anotar esto</th>
<th style="text-align: left;">Anote esto</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Subrayar el hallazgo principal</td>
<td style="text-align: left;">“instala la brecha”</td>
</tr>
<tr class="even">
<td style="text-align: left;">Escribir “importante” al margen</td>
<td style="text-align: left;">“aquí descansa toda la inferencia”</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Resumir el párrafo en dos líneas</td>
<td style="text-align: left;">“concede y limita”</td>
</tr>
</tbody>
</table>
<p>Tres palabras por párrafo bastan. Un texto anotado por función se reutiliza en dos años; uno subrayado, no.</p>
</section>

<section id="actividad-1-reconstrucción-en-cinco-frases" class="title-slide slide level1 center">
<h1>Actividad 1: reconstrucción en cinco frases</h1>
<p>Ocho minutos, trabajo individual, a mano, sobre el resumen y la introducción de Raveau y otros.</p>
<blockquote>
<p>El texto sostiene que ___. Lo sostiene porque ___ y porque ___. La evidencia consiste en ___. Esto solo funciona si ___. Reconoce que ___ y responde ___.</p>
</blockquote>
<p>Escriban sin volver a la lámina donde ya aparece resuelto. Comparar después es parte del ejercicio.</p>
</section>

<section id="revisión-entre-pares-tres-preguntas" class="title-slide slide level1 center">
<h1>Revisión entre pares: tres preguntas</h1>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Pregunta que le hago a mi compañero</th>
<th style="text-align: left;">Respuesta que no sirve</th>
<th style="text-align: left;">Respuesta que sí sirve</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">¿Lo que reconstruiste es una tesis o un tema?</td>
<td style="text-align: left;">“Está bien planteado”</td>
<td style="text-align: left;">“Nadie podría negar eso; falta decir a qué explicación derrota”</td>
</tr>
<tr class="even">
<td style="text-align: left;">¿Lo que escribiste como garantía es realmente una garantía?</td>
<td style="text-align: left;">“Sí, porque usa una regresión multinomial”</td>
<td style="text-align: left;">“Eso es el método; la premisa es que el puntaje del codificador es populismo”</td>
</tr>
<tr class="odd">
<td style="text-align: left;">¿Qué contraejemplo derriba la afirmación?</td>
<td style="text-align: left;">“No se me ocurre ninguno”</td>
<td style="text-align: left;">“Si el modelo predice al codificador y no al fenómeno, todo el argumento cae”</td>
</tr>
</tbody>
</table>
<p>Siete minutos, dos pares y un trío. No se corrige redacción.</p>
</section>

<section id="actividad-2-caza-de-garantías" class="title-slide slide level1 center">
<h1>Actividad 2: caza de garantías</h1>
<p>Cuatro minutos de escritura individual sobre los dos artículos ya reconstruidos, y luego plenario.</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Pregunta</th>
<th style="text-align: left;">Qué debe quedar escrito</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Primera</td>
<td style="text-align: left;">Qué trata cada texto como no problemático y el otro convierte en su objeto central</td>
</tr>
<tr class="even">
<td style="text-align: left;">Segunda</td>
<td style="text-align: left;">Qué autoriza a Varela a llegar hasta el estudiante individual y qué detiene a Raveau antes del líder</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tercera</td>
<td style="text-align: left;">Qué pregunta necesita las dos garantías al mismo tiempo para tener sentido</td>
</tr>
</tbody>
</table>
<p>Cierre: cada uno enuncia en voz alta la tensión de garantías que reconoce dentro de su propio problema de tesis.</p>
</section>

<section id="fenómenos-que-debe-vigilar-en-su-propia-lectura" class="title-slide slide level1 center">
<h1>Fenómenos que debe vigilar en su propia lectura</h1>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Fenómeno</th>
<th style="text-align: left;">Cómo se manifiesta en su apunte</th>
<th style="text-align: left;">Cómo se corrige</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Lectura confirmatoria</td>
<td style="text-align: left;">Encuentra en el texto justo lo que esperaba encontrar</td>
<td style="text-align: left;">Reconstruya el argumento completo antes de emitir cualquier juicio</td>
</tr>
<tr class="even">
<td style="text-align: left;">Deslizamiento de la afirmación</td>
<td style="text-align: left;">Al resumir, la tesis se vuelve más general y por eso deja de ser discutible</td>
<td style="text-align: left;">Vuelva al final de la introducción, que es donde suele estar la formulación estricta</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Método puesto en lugar de premisa</td>
<td style="text-align: left;">Escribió el diseño empírico en la casilla de la garantía</td>
<td style="text-align: left;">Oblíguese a completar la frase “esto solo funciona si…”</td>
</tr>
<tr class="even">
<td style="text-align: left;">Restricción convertida en concepto</td>
<td style="text-align: left;">Un límite de datos aparece en el texto como si fuera una delimitación teórica</td>
<td style="text-align: left;">Pregunte siempre por qué quedó fuera lo que quedó fuera</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Armonía prematura</td>
<td style="text-align: left;">Concluye que las dos disciplinas se complementan</td>
<td style="text-align: left;">Busque primero en qué difieren respecto de lo que cuenta como prueba</td>
</tr>
</tbody>
</table>
<p>Los tres primeros aparecen en casi todos los primeros intentos. Los dos últimos hunden tesis interdisciplinarias completas.</p>
</section>

<section id="lo-que-tienen-que-hacer-esta-semana" class="title-slide slide level1 center">
<h1>Lo que tienen que hacer esta semana</h1>
<p>El ejercicio de hoy usó dos textos que elegí yo y un problema que no es el suyo. La tarea traslada el mismo procedimiento a su tesis, que es donde cuesta, porque ahí ustedes ya tienen una respuesta preferida y la reconstrucción tiende a acomodarse a ella sin que lo noten.</p>
</section>

<section id="tarea-y-rúbrica" class="title-slide slide level1 center">
<h1>Tarea y rúbrica</h1>
<p>Dos textos arbitrados de disciplinas distintas sobre su problema de tesis. Reconstrucción en cinco frases de cada uno, un párrafo que identifique lo que cada uno trata como no problemático y el otro problematiza, y un párrafo con una pregunta condicional derivada de esa tensión. Máximo 900 palabras, en digital y en papel, porque se revisa entre pares en la sesión 4. Queda prohibida la fórmula del vacío en la literatura.</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Criterio</th>
<th style="text-align: left;">Se cumple cuando</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Fidelidad</td>
<td style="text-align: left;">La reconstrucción corresponde a lo que el texto dice y no a lo que usted esperaba que dijera</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afirmación</td>
<td style="text-align: left;">La tesis reconstruida es discutible y nombra la explicación rival que derrota</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Garantía</td>
<td style="text-align: left;">Lo que aparece como garantía es una premisa sobre el mundo, no una descripción del método</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tensión</td>
<td style="text-align: left;">El desacuerdo identificado es sobre qué cuenta como prueba, no sobre resultados distintos</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pregunta</td>
<td style="text-align: left;">Es condicional, está delimitada y no apela a la ausencia de literatura previa</td>
</tr>
<tr class="even">
<td style="text-align: left;">Escritura</td>
<td style="text-align: left;">La prosa es clara y el texto respeta el límite de palabras</td>
</tr>
</tbody>
</table>
</section>

<section id="lo-que-se-lleva-de-esta-hora" class="title-slide slide level1 center">
<h1>Lo que se lleva de esta hora</h1>
<p>Las disciplinas son infraestructuras de evaluación, no etiquetas. Deciden quién arbitra su artículo, en qué cuartil queda, con qué estándar se acredita su programa y qué grupo de Fondecyt lee su proyecto.</p>
<p>Dos artículos rigurosos de campos distintos hicieron hoy el mismo movimiento sin declararlo: convirtieron un constructo disputado en el producto de un instrumento. Uno detuvo la categoría antes del individuo; el otro la llevó hasta la escuela.</p>
<p>Esa diferencia decide política pública, no está argumentada en ninguno de los dos, y escribirla es su trabajo.</p>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p>Mauricio Apablaza - Sesión 2 y 3 - Multidisciplina y Meta-lectura</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="clase03_metalectura_presentacion-2_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="clase03_metalectura_presentacion-2_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="clase03_metalectura_presentacion-2_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="clase03_metalectura_presentacion-2_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="clase03_metalectura_presentacion-2_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="clase03_metalectura_presentacion-2_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="clase03_metalectura_presentacion-2_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="clase03_metalectura_presentacion-2_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="clase03_metalectura_presentacion-2_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="clase03_metalectura_presentacion-2_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
</body></html>
